---
language: "python"
python:
  - "3.7"

# Install python packages for ansible and linters.
install:
  - "pip install -r requirements.txt"

# Perform pre-checks
before_script:
  - "make lint"

# Perform runbook testing with mock ASA inputs. TODO
script:
  - "true"
